# Generated by Django 6.0.5 on 2026-05-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_generalsettings_generalsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsetting',
            old_name='descriptrion',
            new_name='description',
        ),
    ]
