# Generated by Django 6.0.5 on 2026-05-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_descriptrion_generalsetting_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'ordering': ['name'], 'verbose_name': 'General Setting', 'verbose_name_plural': 'General Settings'},
        ),
    ]
