# Generated by Django 6.0.5 on 2026-05-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
